[package]
name = "astro-epd-display"
version = "0.0.1"
edition = "2021"
authors = ["Display interface for EPD"]


[dependencies]
embedded-graphics = "0.8.1"
embedded-hal = "1.0.0"
epd-waveshare = "0.6.0"
linux-embedded-hal = "0.4.0"
rpi_embedded = { version = "0.1.0", features = ["embedded-hal"] }
